### GET all minions (Check your current list)
GET http://localhost:4001/api/minions

###

### POST a new minion 
POST http://localhost:4001/api/minions
Content-Type: application/json

{
  "name": "Kevin",
  "title": "Lead Scientist",
  "salary": 50000
}

###

### PUT (Update) an existing minion
PUT http://localhost:4001/api/minions/1
Content-Type: application/json

{
  "id": "1",
  "name": "Stuart",
  "title": "Lead Guitarist",
  "salary": 55000
}

#########################################################################################
### GET all ideas
GET http://localhost:4001/api/ideas

###

### GET a single idea by ID
GET http://localhost:4001/api/ideas/5

### POST a new idea
# This should succeed if your Million Dollar Middleware is working
POST http://localhost:4001/api/ideas
Content-Type: application/json

{
  "name": "New Tech Startup",
  "description": "An AI-powered tutor for students in Sydney.",
  "numWeeks": 100,
  "weeklyRevenue": 20000
}

###

### POST a "Bad" idea
# This should fail (400) if your Million Dollar Middleware is working 
# (10 * 10 is less than 1,000,000)
POST http://localhost:4001/api/ideas
Content-Type: application/json

{
  "name": "Abella",
  "description": "How cool it is that you mentioned Parramatta.",
  "numWeeks": 11,
  "weeklyRevenue": 60
}

###

### PUT (Update) an existing idea
# Remember to change '1' to a real ID from your GET request
PUT http://localhost:4001/api/ideas/11
Content-Type: application/json

{
  "id": "11",
  "name": "Spotify",
  "description": "Streaming music over the internet. ",
  "numWeeks": 125,
  "weeklyRevenue": 15000
}

###

### DELETE an idea
# Change '1' to a real ID
DELETE http://localhost:4001/api/ideas/11

##################################################################################
### GET all meetings
GET http://localhost:4001/api/meetings

### POST (Create) a new meeting
POST http://localhost:4001/api/meetings

###

### DELETE all meetings
DELETE http://localhost:4001/api/meetings

####################################################################
### Get all work for a specific minion
# Replace :minionId with a known ID from your database
GET http://localhost:4001/api/minions/:minionId/work

###

### Create new work for a minion
POST http://localhost:4001/api/minions/1/work
Content-Type: application/json

{
  "title": "Clean the Lab",
  "description": "Scrub the floors until they shine.",
  "hours": 5,
  "minionId": ":minionId"
}

###

### Update existing work for a minion
# Note: The :workId must exist for the specified :minionId
PUT http://localhost:4001/api/minions/:minionId/work/:workId
Content-Type: application/json

{
  "id": ":workId",
  "title": "Deep Clean the Lab",
  "description": "Scrub the floors AND the ceiling.",
  "hours": 8,
  "minionId": ":minionId"
}

###

### Delete work from a minion's backlog
DELETE http://localhost:4001/api/minions/:minionId/work/:workId